networks:
  web:
    external: true

services:
  selenium:
    container_name: ${SELENIUM_CONTAINER_NAME}
    hostname: selenium
    build:
      context: .
      dockerfile: Docker/Php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - ./:/var/www/src
    working_dir: /var/www/src
    networks:
      - web
    privileged: true
    shm_size: 4g
    command: ["sleep", "infinity"]

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: ${CHROME_CONTAINER_NAME}
    hostname: chrome
    environment:
      VNC_NO_PASSWORD: 1
      SE_CHROME_ARGS: >
        --incognito
    networks:
      - web
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - web
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASSWORD:-root}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
 mysql_data: